name: build offload apk
on:
  push:
    branches:
      - *
    tags:
      - *
  create:
    tags:
      - v*


env:
  RUN: docker run --rm apks /bin/sh -c
  BUILD: |
    docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile) || true
    docker pull docker.io/commaai/openpilot-apks:latest || true
    docker build --cache-from docker.io/commaai/openpilot-apks:latest -t apks -f Dockerfile .
  CACHE_NAME: cache-image


jobs:
  offroad:
    name: offroad
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: eval "$BUILD"
      - name: Build offroad apk
        run: docker run --name apks apks /bin/sh -c "cd offroad && ./build.sh"
      - name: Copy artifacts
        run: docker cp apks:/tmp/openpilot/apks/offroad/ai.comma.plus.offroad.apk ai.comma.plus.offroad.apk
      - uses: actions/upload-artifact@v2
        with:
          name: ai.comma.plus.offroad.apk
          path: ai.comma.plus.offroad.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ai.comma.plus.offroad.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
